import{NextResponse}from"next/server";import{requireAdmin}from"@/lib/authorization";import{createAdminClient}from"@/lib/supabase/admin";import{getShopifyReadiness}from"@/lib/shopify-config";import{backupTables}from"@/lib/backup-manifest";import{summarizeProductionSmokeTest,type SmokeCheck}from"@/lib/production-smoke-test";

async function runSmokeTest(){const supabase=createAdminClient();const checks:SmokeCheck[]=[];const core=["contacts","contact_research_evidence","outreach_drafts","sales_pipeline","shopify_sync_runs","shopify_orders","shopify_products","reorder_requests","retailer_portal_access","launch_verifications","launch_smoke_runs","audit_events","app_user_roles"];
const coreResults=await Promise.all(core.map(table=>supabase.from(table).select(table==="app_user_roles"||table==="retailer_portal_access"?"user_id":"id",{head:true,count:"exact"})));core.forEach((table,index)=>checks.push({name:`Database: ${table}`,passed:!coreResults[index].error,detail:coreResults[index].error?"Table is unavailable or unreadable.":`${coreResults[index].count??0} rows readable.`}));
const{count:admins,error:adminError}=await supabase.from("app_user_roles").select("user_id",{head:true,count:"exact"}).eq("role","admin");checks.push({name:"Administrator assignment",passed:!adminError&&(admins??0)>0,detail:adminError?"Unable to inspect administrator roles.":`${admins??0} administrator account(s) assigned.`});
const{count:failedSyncs,error:syncError}=await supabase.from("shopify_sync_runs").select("id",{head:true,count:"exact"}).eq("status","failed");checks.push({name:"Shopify sync failures",passed:!syncError&&(failedSyncs??0)===0,detail:syncError?"Unable to inspect sync history.":`${failedSyncs??0} failed sync run(s).`});
const backupResults=await Promise.all(backupTables.map(table=>supabase.from(table).select("*",{head:true,count:"exact"})));checks.push({name:"Backup export readiness",passed:backupResults.every(result=>!result.error),detail:backupResults.every(result=>!result.error)?`All ${backupTables.length} backup tables are readable.`:"One or more backup tables cannot be read."});
const shopify=getShopifyReadiness(process.env);checks.push({name:"Shopify credentials",passed:shopify.configured,detail:shopify.configured?"Server-only Shopify configuration is present.":"Shopify remains unconfigured; no live sync can be verified yet."});
checks.push({name:"Outbound automation",passed:true,detail:"Smoke test performs reads only and does not send outreach or create Shopify orders."});return{checks,summary:summarizeProductionSmokeTest(checks),checkedAt:new Date().toISOString()};}

export async function GET(request:Request){try{await requireAdmin();const{searchParams}=new URL(request.url);if(searchParams.get("history")==="1"){const supabase=createAdminClient();const{data,error}=await supabase.from("launch_smoke_runs").select("id,checked_at,status,passed,total,failed,recorded_by,created_at").order("checked_at",{ascending:false}).limit(12);if(error)throw error;return NextResponse.json({runs:data??[]},{headers:{"cache-control":"no-store"}});}return NextResponse.json(await runSmokeTest(),{headers:{"cache-control":"no-store"}});}catch(error){const message=error instanceof Error?error.message:"Unable to run production smoke test.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Administrator access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:500});}}

export async function POST(){try{const{user}=await requireAdmin();const result=await runSmokeTest();const supabase=createAdminClient();const{data,error}=await supabase.rpc("record_launch_smoke_run",{p_actor_id:user.id,p_checked_at:result.checkedAt,p_status:result.summary.status,p_passed:result.summary.passed,p_total:result.summary.total,p_failed:result.summary.failed,p_checks:result.checks});if(error)throw error;return NextResponse.json({...result,recorded:true,runId:data});}catch(error){const message=error instanceof Error?error.message:"Unable to record production smoke test.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Administrator access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:500});}}
