import{NextResponse}from"next/server";import{requireAdmin}from"@/lib/authorization";import{createAdminClient}from"@/lib/supabase/admin";import{getShopifyReadiness}from"@/lib/shopify-config";import{backupTables}from"@/lib/backup-manifest";import{summarizeProductionSmokeTest,type SmokeCheck}from"@/lib/production-smoke-test";

async function runSmokeTest(){const supabase=createAdminClient();const checks:SmokeCheck[]=[];const core=["contacts","contact_research_evidence","outreach_drafts","outreach_delivery_intents","outreach_delivery_attempts","outreach_delivery_events","outreach_replies","conversation_recommendations","sales_pipeline","sales_tasks","sales_command_decisions","sales_operating_review_snapshots","sales_operating_targets","shopify_sync_runs","shopify_orders","shopify_products","reorder_requests","retailer_portal_access","launch_verifications","launch_smoke_runs","launch_remediations","pilot_health_reviews","backup_recovery_drills","audit_events","app_user_roles"];
const coreResults=await Promise.all(core.map(table=>supabase.from(table).select(table==="app_user_roles"||table==="retailer_portal_access"?"user_id":"id",{head:true,count:"exact"})));core.forEach((table,index)=>checks.push({name:`Database: ${table}`,passed:!coreResults[index].error,detail:coreResults[index].error?"Table is unavailable or unreadable.":`${coreResults[index].count??0} rows readable.`}));
const conversationSchema=await Promise.all([supabase.from("conversation_recommendations").select("id,response_outreach_draft_id,response_draft_created_at,task_id,task_applied_at,pipeline_applied_at",{head:true,count:"exact"}),supabase.from("outreach_drafts").select("id,purpose,thread_key",{head:true,count:"exact"}),supabase.from("outreach_replies").select("id,matched_by,manual_matched_by,manual_matched_at,manual_match_note",{head:true,count:"exact"})]);checks.push({name:"Milestone 13 schema",passed:conversationSchema.every(result=>!result.error),detail:conversationSchema.every(result=>!result.error)?"Conversation recommendations, manual reply matching, task/pipeline evidence, and response-draft handoff columns are readable through migration 050.":"Milestone 13 schema is incomplete. Apply migrations 046 through 050 before enabling conversation intelligence."});
const commandSchema=await supabase.from("sales_command_decisions").select("id,item_fingerprint,item_id,item_kind,contact_id,item_title,item_action,item_reason,outcome,note,defer_until,decided_by,decided_at,updated_at",{head:true,count:"exact"});checks.push({name:"Milestone 16 schema",passed:!commandSchema.error,detail:commandSchema.error?"Milestone 16 schema is incomplete. Apply migration 051 before enabling command-center outcomes.":"Audited command-center decisions are readable through migration 051."});
const reviewSchema=await supabase.from("sales_operating_review_snapshots").select("id,period,as_of_date,current_start,current_end,previous_start,previous_end,review_payload,payload_hash,recorded_by,recorded_at",{head:true,count:"exact"});checks.push({name:"Milestone 18 schema",passed:!reviewSchema.error,detail:reviewSchema.error?"Milestone 18 schema is incomplete. Apply migration 052 before recording immutable operating-review snapshots.":"Immutable operating-review snapshot evidence is readable through migration 052."});
const targetSchema=await supabase.from("sales_operating_targets").select("id,period,metric,target_value,effective_from,effective_to,note,set_by,set_at",{head:true,count:"exact"});checks.push({name:"Milestone 20 schema",passed:!targetSchema.error,detail:targetSchema.error?"Milestone 20 schema is incomplete. Apply migration 053 before enabling operating targets.":"Versioned operating targets are readable through migration 053."});
const{count:admins,error:adminError}=await supabase.from("app_user_roles").select("user_id",{head:true,count:"exact"}).eq("role","admin");checks.push({name:"Administrator assignment",passed:!adminError&&(admins??0)>0,detail:adminError?"Unable to inspect administrator roles.":`${admins??0} administrator account(s) assigned.`});
const{count:failedSyncs,error:syncError}=await supabase.from("shopify_sync_runs").select("id",{head:true,count:"exact"}).eq("status","failed");checks.push({name:"Shopify sync failures",passed:!syncError&&(failedSyncs??0)===0,detail:syncError?"Unable to inspect sync history.":`${failedSyncs??0} failed sync run(s).`});
const backupResults=await Promise.all(backupTables.map(table=>supabase.from(table).select("*",{head:true,count:"exact"})));checks.push({name:"Backup export readiness",passed:backupResults.every(result=>!result.error),detail:backupResults.every(result=>!result.error)?`All ${backupTables.length} backup tables are readable.`:"One or more backup tables cannot be read."});
const shopify=getShopifyReadiness(process.env);checks.push({name:"Shopify credentials",passed:shopify.configured,detail:shopify.configured?"Server-only Shopify configuration is present.":"Shopify remains unconfigured; no live sync can be verified yet."});
checks.push({name:"Outbound automation",passed:true,detail:"Smoke test performs reads only and does not send outreach, approve drafts, mutate the sales pipeline, complete follow-up tasks, record command-center decisions, record operating-review snapshots, set operating targets, or create Shopify orders."});return{checks,summary:summarizeProductionSmokeTest(checks),checkedAt:new Date().toISOString()};}
export async function GET(request:Request){try{await requireAdmin();const{searchParams}=new URL(request.url);if(searchParams.get("history")==="1"){const supabase=createAdminClient();const{data,error}=await supabase.from("launch_smoke_runs").select("id,checked_at,status,passed,total,failed,recorded_by,created_at").order("checked_at",{ascending:false}).limit(12);if(error)throw error;return NextResponse.json({runs:data??[]},{headers:{"cache-control":"no-store"}});}return NextResponse.json(await runSmokeTest(),{headers:{"cache-control":"no-store"}});}catch(error){const message=error instanceof Error?error.message:"Unable to run production smoke test.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Administrator access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:500});}}
export async function POST(){try{const{user}=await requireAdmin();const result=await runSmokeTest();const supabase=createAdminClient();const{data,error}=await supabase.rpc("record_launch_smoke_run",{p_actor_id:user.id,p_checked_at:result.checkedAt,p_status:result.summary.status,p_passed:result.summary.passed,p_total:result.summary.total,p_failed:result.summary.failed,p_checks:result.checks});if(error)throw error;return NextResponse.json({...result,recorded:true,runId:data});}catch(error){const message=error instanceof Error?error.message:"Unable to record production smoke test.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Administrator access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:500});}}
