import{NextResponse}from"next/server";import{z}from"zod";import{createAdminClient}from"@/lib/supabase/admin";import{requireAdmin,requireSales}from"@/lib/authorization";import{draftStatusAuditAction}from"@/lib/draft-audit";import{outreachDeliveryHash}from"@/lib/outreach-delivery";import{canTransitionDraft,outreachEligibility,transitionNeedsAdmin,type DraftStatus,type OutreachChannel}from"@/lib/outreach-approval";
const saveSchema=z.object({contact_id:z.string().uuid(),channel:z.enum(["email","linkedin","text"]).default("email"),purpose:z.enum(["initial_outreach","reorder_follow_up"]).default("initial_outreach"),subject:z.string().trim().min(1).max(300),body:z.string().trim().min(1).max(10000),status:z.enum(["draft","awaiting_approval"]).default("draft")});
const statusSchema=z.object({id:z.string().uuid(),status:z.enum(["draft","awaiting_approval","approved","rejected","sent"])});
async function eligibility(supabase:ReturnType<typeof createAdminClient>,contactId:string,channel:OutreachChannel){
 const[{data:contact,error:contactError},{data:suppression,error:suppressionError},{data:consent,error:consentError}]=await Promise.all([
  supabase.from("contacts").select("email,phone,linkedin_url").eq("id",contactId).single(),
  supabase.from("suppressions").select("id").eq("contact_id",contactId).eq("channel",channel).maybeSingle(),
  channel==="text"?supabase.from("contact_channel_consents").select("status").eq("contact_id",contactId).eq("channel","text").maybeSingle():Promise.resolve({data:null,error:null}),
 ]);if(contactError)throw contactError;if(suppressionError)throw suppressionError;if(consentError)throw consentError;
 return outreachEligibility({channel,email:contact.email,phone:contact.phone,linkedinUrl:contact.linkedin_url,suppressed:Boolean(suppression),textConsent:consent?.status==="opted_in"});
}
export async function GET(){try{await requireSales();const supabase=createAdminClient();const{data,error}=await supabase.from("outreach_drafts").select("*").order("updated_at",{ascending:false}).limit(500);if(error)throw error;return NextResponse.json({drafts:data??[]})}catch(error){return failure(error,"Unable to load drafts.",500)}}
export async function POST(request:Request){try{const{user}=await requireSales();const body=saveSchema.parse(await request.json());const supabase=createAdminClient();const allowed=await eligibility(supabase,body.contact_id,body.channel);if(!allowed.eligible)return NextResponse.json({error:allowed.reason},{status:400});const{data:existing,error:existingError}=await supabase.from("outreach_drafts").select("id,status").eq("contact_id",body.contact_id).eq("channel",body.channel).eq("purpose",body.purpose).eq("thread_key","default").maybeSingle();if(existingError)throw existingError;if(existing&&(existing.status==="approved"||existing.status==="sent"))return NextResponse.json({error:"Approved or sent outreach is immutable. Create a new outreach purpose/version instead of editing the approved content."},{status:409});const{data,error}=await supabase.from("outreach_drafts").upsert({...body,thread_key:"default",created_by:user.id,updated_at:new Date().toISOString()},{onConflict:"contact_id,channel,purpose,thread_key"}).select("*").single();if(error)throw error;await audit(supabase,data,user.id);return NextResponse.json({draft:data})}catch(error){return failure(error,"Unable to save draft.",400)}}
export async function PATCH(request:Request){try{const body=statusSchema.parse(await request.json());const auth=transitionNeedsAdmin(body.status)?await requireAdmin():await requireSales();const supabase=createAdminClient();const{data:existing,error:loadError}=await supabase.from("outreach_drafts").select("*").eq("id",body.id).single();if(loadError)throw loadError;if(!canTransitionDraft(existing.status as DraftStatus,body.status))return NextResponse.json({error:`Draft cannot move from ${existing.status} to ${body.status}.`},{status:409});if(body.status==="approved"||body.status==="sent"){const allowed=await eligibility(supabase,existing.contact_id,existing.channel as OutreachChannel);if(!allowed.eligible)return NextResponse.json({error:allowed.reason},{status:409})}
 if(body.status==="sent"){
  if(existing.channel!=="email"&&existing.channel!=="linkedin")return NextResponse.json({error:"Only email and LinkedIn manual confirmations are enabled in the delivery ledger."},{status:409});
  const{data:contact,error:contactError}=await supabase.from("contacts").select("email,linkedin_url").eq("id",existing.contact_id).single();if(contactError)throw contactError;const recipient=existing.channel==="email"?contact.email:contact.linkedin_url;if(!recipient)return NextResponse.json({error:"A verified channel recipient is required."},{status:409});
  const contentHash=outreachDeliveryHash({channel:existing.channel,recipient,subject:existing.subject,body:existing.body});
  const{data:prepared,error:prepareError}=await supabase.rpc("prepare_outreach_delivery_intent",{p_draft_id:existing.id,p_actor_id:auth.user.id,p_content_hash:contentHash});if(prepareError)throw prepareError;
  const intentId=(prepared as{intent_id?:string}|null)?.intent_id;if(!intentId)throw new Error("Delivery intent was not created.");
  const{error:confirmError}=await supabase.rpc("confirm_outreach_delivery_intent",{p_intent_id:intentId,p_actor_id:auth.user.id,p_delivery_method:"manual",p_provider_message_id:null,p_confirmation_note:"Confirmed sent through the approved outreach workflow."});if(confirmError)throw confirmError;
  const{data:sentDraft,error:sentError}=await supabase.from("outreach_drafts").select("*").eq("id",existing.id).single();if(sentError)throw sentError;return NextResponse.json({draft:sentDraft,deliveryIntentId:intentId});
 }
 const{data,error}=await supabase.from("outreach_drafts").update({status:body.status,updated_at:new Date().toISOString()}).eq("id",body.id).eq("status",existing.status).select("*").single();if(error)throw error;await audit(supabase,data,auth.user.id);return NextResponse.json({draft:data})}catch(error){return failure(error,"Unable to update draft.",400)}}
async function audit(supabase:ReturnType<typeof createAdminClient>,data:{id:string;contact_id:string;channel:string;purpose:string;status:DraftStatus},actorId:string){const{error}=await supabase.from("audit_events").insert({action:draftStatusAuditAction(data.status),entity_type:"outreach_draft",entity_id:data.id,actor_id:actorId,metadata:{contactId:data.contact_id,channel:data.channel,purpose:data.purpose,status:data.status}});if(error)throw error}
function failure(error:unknown,fallback:string,defaultStatus:number){const message=error instanceof Error?error.message:fallback;return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Administrator approval is required for this decision.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:defaultStatus})}
