import{NextResponse}from"next/server";import{createAdminClient}from"@/lib/supabase/admin";import{extractEmailAddress,parseMessageReferences,verifyResendWebhook,type ResendWebhookEvent}from"@/lib/resend-webhook";import{retrieveReceivedEmail}from"@/lib/resend-receiving";
export const runtime="nodejs";
function jsonError(message:string,status:number){return NextResponse.json({error:message},{status});}
async function findIntentByMessageId(supabase:ReturnType<typeof createAdminClient>,ids:string[]){for(const id of ids){const{data,error}=await supabase.from("outreach_delivery_intents").select("id,contact_id,provider_message_id,provider_rfc_message_id").eq("provider_rfc_message_id",id).maybeSingle();if(error)throw error;if(data)return data;}return null;}
export async function POST(request:Request){const secret=process.env.RESEND_WEBHOOK_SECRET;if(!secret)return jsonError("Webhook verification is not configured.",503);const payload=await request.text();const eventId=request.headers.get("svix-id");if(!verifyResendWebhook({payload,id:eventId,timestamp:request.headers.get("svix-timestamp"),signature:request.headers.get("svix-signature"),secret}))return jsonError("Invalid webhook signature.",401);let event:ResendWebhookEvent;try{event=JSON.parse(payload)as ResendWebhookEvent}catch{return jsonError("Invalid webhook payload.",400)}if(!eventId||!event?.type||!event?.data)return jsonError("Incomplete webhook payload.",400);const supabase=createAdminClient();
 if(event.type==="email.received")return handleReceived(supabase,eventId,event);
 const providerMessageId=typeof event.data.email_id==="string"?event.data.email_id:null;const messageId=typeof event.data.message_id==="string"?event.data.message_id:null;let intent:null|{id:string;contact_id:string}=null;if(providerMessageId){const{data,error}=await supabase.from("outreach_delivery_intents").select("id,contact_id").eq("provider_message_id",providerMessageId).maybeSingle();if(error)throw error;intent=data;}
 const{error:eventError}=await supabase.from("outreach_delivery_events").insert({provider:"resend",provider_event_id:eventId,event_type:event.type,intent_id:intent?.id??null,provider_message_id:providerMessageId,message_id:messageId,occurred_at:event.created_at,payload:{to:event.data.to??null,subject:event.data.subject??null,bounce:event.data.bounce??null}});if(eventError){if(eventError.code==="23505")return NextResponse.json({ok:true,duplicate:true});throw eventError;}
 if(intent&&messageId){const{error}=await supabase.from("outreach_delivery_intents").update({provider_rfc_message_id:messageId}).eq("id",intent.id).is("provider_rfc_message_id",null);if(error&&error.code!=="23505")throw error;}
 if(intent&&(event.type==="email.complained"||(event.type==="email.bounced"&&typeof event.data.bounce==="object"&&event.data.bounce!==null&&String((event.data.bounce as Record<string,unknown>).type??"").toLowerCase()==="permanent"))){const reason=event.type==="email.complained"?"provider_complaint":"provider_permanent_bounce";const{error}=await supabase.from("suppressions").upsert({contact_id:intent.contact_id,channel:"email",reason},{onConflict:"contact_id,channel"});if(error)throw error;}
 return NextResponse.json({ok:true,matched:Boolean(intent)});
}
async function handleReceived(supabase:ReturnType<typeof createAdminClient>,eventId:string,event:ResendWebhookEvent){const receivedId=typeof event.data.email_id==="string"?event.data.email_id:null;if(!receivedId)return jsonError("Received email id is missing.",400);const{data:existing,error:existingError}=await supabase.from("outreach_replies").select("id").eq("provider_event_id",eventId).maybeSingle();if(existingError)throw existingError;if(existing)return NextResponse.json({ok:true,duplicate:true});const apiKey=process.env.RESEND_API_KEY;if(!apiKey)return jsonError("Inbound email retrieval is not configured.",503);const received=await retrieveReceivedEmail(apiKey,receivedId);const refs=parseMessageReferences(received.headers??{});const candidates=[...(refs.inReplyTo?[refs.inReplyTo]:[]),...refs.references].filter((v,i,a)=>a.indexOf(v)===i);const intent=await findIntentByMessageId(supabase,candidates);const matchedBy=intent?(refs.inReplyTo&&intent.provider_rfc_message_id===refs.inReplyTo?"in_reply_to":"references"):"unmatched";const fromEmail=extractEmailAddress(received.from);const{data:reply,error:replyError}=await supabase.from("outreach_replies").insert({provider:"resend",provider_received_email_id:received.id,provider_event_id:eventId,intent_id:intent?.id??null,contact_id:intent?.contact_id??null,from_email:fromEmail,to_emails:received.to??[],subject:received.subject??"",text_body:received.text?.slice(0,50000)??null,message_id:received.message_id??null,in_reply_to:refs.inReplyTo,reference_ids:refs.references,received_at:received.created_at,matched_by:matchedBy}).select("id").single();if(replyError)throw replyError;const{error:eventError}=await supabase.from("outreach_delivery_events").insert({provider:"resend",provider_event_id:eventId,event_type:event.type,intent_id:intent?.id??null,provider_message_id:received.id,message_id:received.message_id??null,occurred_at:event.created_at,payload:{from:fromEmail,to:received.to??[],subject:received.subject??"",matched_by:matchedBy,reply_id:reply.id}});if(eventError&&eventError.code!=="23505")throw eventError;await supabase.from("audit_events").insert({action:"outreach_reply_received",entity_type:"outreach_reply",entity_id:reply.id,actor_id:null,metadata:{intent_id:intent?.id??null,contact_id:intent?.contact_id??null,matched_by:matchedBy,from:fromEmail}});return NextResponse.json({ok:true,replyId:reply.id,matched:Boolean(intent),matchedBy});}
