"use client";
import{useCallback,useEffect,useState}from"react";
type Gate={name:string;passed:boolean;required:boolean;detail:string};
type Summary={decision:"not_ready"|"pilot_ready"|"launch_ready";passed:number;requiredBlocked:number;optionalPending:number};
type VerificationKey="invitation"|"approval_flow"|"backup_restore";
type Payload={gates:Gate[];summary:Summary;checkedAt:string};
const verificationMeta:Record<VerificationKey,{title:string;prompt:string}>={invitation:{title:"Invitation round-trip",prompt:"Describe the real invited account and successful sign-in/account-setup result."},approval_flow:{title:"Approval safeguards",prompt:"Describe the outreach/reconciliation/reorder checks and the audit events you confirmed."},backup_restore:{title:"Backup and recovery",prompt:"Describe the backup export, validator result, and record-count review."}};
export function LaunchVerificationPanel(){const[data,setData]=useState<Payload|null>(null);const[notes,setNotes]=useState<Record<VerificationKey,string>>({invitation:"",approval_flow:"",backup_restore:""});const[busy,setBusy]=useState<VerificationKey|null>(null);const[error,setError]=useState("");const load=useCallback(async()=>{const response=await fetch("/api/launch-readiness",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error??"Unable to load launch readiness.");setData(result);},[]);useEffect(()=>{load().catch(err=>setError(err instanceof Error?err.message:"Unable to load launch readiness."));},[load]);async function record(key:VerificationKey){const note=notes[key].trim();if(note.length<8){setError("Add a short verification note before recording evidence.");return;}if(!window.confirm(`Record ${verificationMeta[key].title} as live-verified? Only continue after the real test has succeeded.`))return;setBusy(key);setError("");try{const response=await fetch("/api/launch-readiness",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({verification:key,note,confirmation:"RECORD_LIVE_VERIFICATION"})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Unable to record launch verification.");setNotes(current=>({...current,[key]:""}));await load();}catch(err){setError(err instanceof Error?err.message:"Unable to record launch verification.");}finally{setBusy(null);}}
if(!data)return <div className="panel">{error?<div className="alert error">{error}</div>:"Loading launch readiness…"}</div>;
return <><div className="panel"><div className="panel-heading"><div><span className="section-label">PRODUCTION READINESS</span><h2>{data.summary.decision.replaceAll("_"," ")}</h2><p>{data.summary.passed} gates passed · {data.summary.requiredBlocked} required blockers · {data.summary.optionalPending} optional items pending</p></div></div>{error&&<div className="alert error">{error}</div>}<div className="activity-list">{data.gates.map(gate=><div className="match-row" key={gate.name}><div><strong>{gate.name}</strong><p>{gate.detail}</p></div><span className={`badge ${gate.passed?"valid":gate.required?"warning":""}`}>{gate.passed?"Passed":gate.required?"Required":"Optional"}</span></div>)}</div></div><div className="panel"><div className="panel-heading"><div><span className="section-label">LIVE EVIDENCE</span><h2>Record completed production checks</h2><p>These controls do not run the test for you. They record an administrator's evidence only after the real workflow succeeds.</p></div></div>{(Object.keys(verificationMeta) as VerificationKey[]).map(key=><div className="match-row" key={key}><div><strong>{verificationMeta[key].title}</strong><p>{verificationMeta[key].prompt}</p><textarea value={notes[key]} maxLength={1000} onChange={event=>setNotes(current=>({...current,[key]:event.target.value}))} placeholder="Verification note"/></div><button disabled={busy!==null||notes[key].trim().length<8} onClick={()=>record(key)}>{busy===key?"Recording…":"Record verification"}</button></div>)}</div></>}
