import{z}from"zod";

const rawCandidateSchema=z.object({company_name:z.string().trim().min(1).max(200),buyer_name:z.string().trim().max(200).nullable(),job_title:z.string().trim().max(200).nullable(),email:z.string().trim().email().max(320).nullable(),linkedin_url:z.string().trim().url().max(1000).nullable(),website:z.string().trim().url().max(1000).nullable(),city:z.string().trim().max(120).nullable(),state:z.string().trim().max(120).nullable(),category:z.string().trim().max(200).nullable(),source_url:z.string().trim().url().max(2000),source_note:z.string().trim().min(8).max(2000),confidence:z.enum(["medium","high"])});
const discoveryOutputSchema=z.object({candidates:z.array(rawCandidateSchema).max(10)});
export type WebProspectCandidate=z.infer<typeof rawCandidateSchema>&{source_type:"linkedin"|"company_website"};
type ResponsesOutputItem={type?:string;content?:Array<{type?:string;text?:string}>;action?:{sources?:Array<{url?:string}>}};
type ResponsesPayload={output?:ResponsesOutputItem[]};

export function canonicalizeSourceUrl(value:string){try{const url=new URL(value);url.hash="";url.hostname=url.hostname.toLowerCase().replace(/^www\./,"");url.pathname=url.pathname.replace(/\/+$/,"/");return url.toString();}catch{return null;}}
function hostname(value:string|null){if(!value)return null;try{return new URL(value).hostname.toLowerCase().replace(/^www\./,"");}catch{return null;}}
export function extractConsultedSources(payload:ResponsesPayload){const sources=new Set<string>();for(const item of payload.output??[]){if(item.type!=="web_search_call")continue;for(const source of item.action?.sources??[]){if(typeof source.url!=="string")continue;const normalized=canonicalizeSourceUrl(source.url);if(normalized)sources.add(normalized);}}return sources;}
export function extractOutputText(payload:ResponsesPayload){for(const item of payload.output??[]){if(item.type!=="message")continue;for(const part of item.content??[]){if(part.type==="output_text"&&typeof part.text==="string")return part.text;}}return null;}
export function validateDiscoveredCandidates(raw:unknown,consultedSources:Set<string>){const parsed=discoveryOutputSchema.parse(raw);const accepted:WebProspectCandidate[]=[];let rejectedSourceCount=0;for(const candidate of parsed.candidates){const source=canonicalizeSourceUrl(candidate.source_url);if(!source||!consultedSources.has(source)){rejectedSourceCount++;continue;}const sourceHost=hostname(candidate.source_url);if(sourceHost?.endsWith("linkedin.com")){accepted.push({...candidate,source_type:"linkedin"});continue;}const websiteHost=hostname(candidate.website);if(!sourceHost||!websiteHost||sourceHost!==websiteHost){rejectedSourceCount++;continue;}accepted.push({...candidate,source_type:"company_website"});}return{candidates:accepted,rejectedSourceCount,totalReturned:parsed.candidates.length};}

const prospectSchema={type:"object",additionalProperties:false,required:["candidates"],properties:{candidates:{type:"array",maxItems:10,items:{type:"object",additionalProperties:false,required:["company_name","buyer_name","job_title","email","linkedin_url","website","city","state","category","source_url","source_note","confidence"],properties:{company_name:{type:"string"},buyer_name:{type:["string","null"]},job_title:{type:["string","null"]},email:{type:["string","null"]},linkedin_url:{type:["string","null"]},website:{type:["string","null"]},city:{type:["string","null"]},state:{type:["string","null"]},category:{type:["string","null"]},source_url:{type:"string"},source_note:{type:"string"},confidence:{type:"string",enum:["medium","high"]}}}}}};

export async function discoverProspectsWithWebSearch(args:{apiKey:string;model:string;criteria:string;limit:number}){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${args.apiKey}`,"content-type":"application/json"},body:JSON.stringify({model:args.model,reasoning:{effort:"low"},tools:[{type:"web_search"}],tool_choice:"auto",include:["web_search_call.action.sources"],input:[{role:"system",content:"You research prospective retail accounts and retail buyers for a beverage sales team. Return only prospects supported by public evidence. Never invent or infer an email address. Use null when a field is not explicitly supported. A candidate source must be either an official company website page for that retailer or a LinkedIn page. The source_url must be a URL actually consulted during this web search. Prefer buyers, category managers, purchasing roles, founders, or owners when publicly supported. Do not send messages or perform outreach."},{role:"user",content:`Find up to ${args.limit} prospective retail accounts or buyers matching these criteria: ${args.criteria}. Focus on actionable, source-backed prospects, and do not pad the result with weak matches.`}],text:{format:{type:"json_schema",name:"prospect_discovery",strict:true,schema:prospectSchema}}})});if(!response.ok){let detail="";try{const body=await response.json() as {error?:{message?:string}};detail=body.error?.message??"";}catch{}throw new Error(detail?`Web discovery provider error: ${detail}`:`Web discovery provider returned HTTP ${response.status}.`);}const payload=await response.json() as ResponsesPayload;const outputText=extractOutputText(payload);if(!outputText)throw new Error("Web discovery provider returned no structured prospect output.");let raw:unknown;try{raw=JSON.parse(outputText);}catch{throw new Error("Web discovery provider returned invalid structured prospect output.");}const sources=extractConsultedSources(payload);const validated=validateDiscoveredCandidates(raw,sources);return{...validated,consultedSourceCount:sources.size};}
