export type CommandLane="act_now"|"today"|"up_next";
export type CommandCenterItem={id:string;kind:"buyer_reply"|"task"|"prospect_review"|"account_action";lane:CommandLane;title:string;action:string;reason:string;priority:number;href:string;contactId?:string|null;relatedSignals:string[];signalCount:number};
export type CommandReply={id:string;contactId?:string|null;companyName?:string|null;receivedAt:string;reviewStatus:string;matchedBy:"in_reply_to"|"references"|"manual_review"|"unmatched";priorityScore:number;priorityReasons:string[]};
export type CommandTask={id:string;contactId:string;companyName?:string|null;title:string;dueAt?:string|null;completedAt?:string|null};
export type CommandProspect={id:string;companyName:string;buyerName?:string|null;confidence:string;status:string;discoveredAt:string};
export type CommandAccountAction={contactId:string;companyName:string;priority:number;action:string;reason:string};
function taskPriority(task:CommandTask,today:string){if(task.completedAt)return 0;if(!task.dueAt)return 45;const due=task.dueAt.slice(0,10);if(due<today)return 85;if(due===today)return 75;return 50;}
function prospectPriority(prospect:CommandProspect,nowMs:number){let score=prospect.confidence==="high"?62:52;const ageHours=Math.max(0,(nowMs-Date.parse(prospect.discoveredAt))/3600000);if(ageHours>=48)score+=10;else if(ageHours>=24)score+=5;return Math.min(80,score);}
function laneForPriority(priority:number):CommandLane{return priority>=80?"act_now":priority>=60?"today":"up_next";}
const laneOrder:Record<CommandLane,number>={act_now:0,today:1,up_next:2};const kindOrder:Record<CommandCenterItem["kind"],number>={buyer_reply:0,task:1,prospect_review:2,account_action:3};
function sortItems(items:CommandCenterItem[]){return items.sort((a,b)=>laneOrder[a.lane]-laneOrder[b.lane]||b.priority-a.priority||kindOrder[a.kind]-kindOrder[b.kind]||a.title.localeCompare(b.title));}
function collapseContactSignals(items:CommandCenterItem[]){const visible:CommandCenterItem[]=[];const primaryByContact=new Map<string,CommandCenterItem>();for(const item of items){if(!item.contactId){visible.push(item);continue;}const existing=primaryByContact.get(item.contactId);if(!existing){primaryByContact.set(item.contactId,item);visible.push(item);continue;}existing.relatedSignals.push(`${item.action} — ${item.reason}`);existing.signalCount+=item.signalCount;}return visible;}
export function buildSalesCommandCenter(input:{today:string;nowMs?:number;replies:CommandReply[];tasks:CommandTask[];prospects:CommandProspect[];accountActions:CommandAccountAction[]}){const nowMs=input.nowMs??Date.now();const items:CommandCenterItem[]=[];const base={relatedSignals:[] as string[],signalCount:1};
 for(const reply of input.replies){if(reply.reviewStatus!=="unreviewed")continue;const priority=100+reply.priorityScore;const unmatched=reply.matchedBy==="unmatched";items.push({...base,relatedSignals:[],id:`reply:${reply.id}`,kind:"buyer_reply",lane:"act_now",title:reply.companyName||"Inbound email",action:unmatched?"Match inbound email to a delivered conversation":"Review buyer reply",reason:reply.priorityReasons.join(" · ")||"Unreviewed buyer reply",priority,href:"/delivery",contactId:reply.contactId});}
 for(const task of input.tasks){const priority=taskPriority(task,input.today);if(!priority)continue;const due=task.dueAt?.slice(0,10);items.push({...base,relatedSignals:[],id:`task:${task.id}`,kind:"task",lane:due&&due<input.today?"act_now":due===input.today?"today":laneForPriority(priority),title:task.companyName||"Sales task",action:task.title,reason:due?due<input.today?`Task overdue since ${due}`:due===input.today?"Task due today":`Task due ${due}`:"Open sales task",priority,href:"/",contactId:task.contactId});}
 for(const prospect of input.prospects){if(prospect.status!=="pending")continue;const priority=prospectPriority(prospect,nowMs);items.push({...base,relatedSignals:[],id:`prospect:${prospect.id}`,kind:"prospect_review",lane:laneForPriority(priority),title:prospect.companyName,action:prospect.buyerName?`Review ${prospect.buyerName}`:"Review prospect evidence",reason:`${prospect.confidence} confidence candidate awaiting human review`,priority,href:"/prospects"});}
 for(const account of input.accountActions){const priority=Math.min(90,Math.max(1,Math.round(account.priority/3)));items.push({...base,relatedSignals:[],id:`account:${account.contactId}`,kind:"account_action",lane:laneForPriority(priority),title:account.companyName,action:account.action,reason:account.reason,priority,href:"/strategy",contactId:account.contactId});}
 const raw=sortItems(items);const visible=collapseContactSignals(raw);const topItems=visible.slice(0,20);return{items:visible,topItems,signalCount:raw.length,lanes:{actNow:topItems.filter(i=>i.lane==="act_now"),today:topItems.filter(i=>i.lane==="today"),upNext:topItems.filter(i=>i.lane==="up_next")},summary:{buyerReplies:raw.filter(i=>i.kind==="buyer_reply").length,openTasks:raw.filter(i=>i.kind==="task").length,prospectReviews:raw.filter(i=>i.kind==="prospect_review").length,accountActions:raw.filter(i=>i.kind==="account_action").length,visiblePriorities:visible.length}};}
