import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireSales } from "@/lib/authorization";

const pipelineSchema=z.object({contact_id:z.string().uuid(),stage:z.enum(["prospect","contacted","sample_planned","sample_sent","follow_up_due","ordered","not_interested"]),next_follow_up_on:z.union([z.literal(""),z.string().date()]),notes:z.string().trim().max(4000),opening_order_value:z.union([z.literal(""),z.coerce.number().min(0).max(10000000)]),ordered_on:z.union([z.literal(""),z.string().date()]),reorder_follow_up_on:z.union([z.literal(""),z.string().date()])});

export async function GET(){try{await requireSales();const supabase=createAdminClient();const{data,error}=await supabase.from("sales_pipeline").select("*").order("updated_at",{ascending:false}).limit(500);if(error)throw error;return NextResponse.json({pipeline:data??[]})}catch(error){const message=error instanceof Error?error.message:"Unable to load pipeline.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Assigned team access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:500})}}

export async function POST(request:Request){try{const{user}=await requireSales();const body=pipelineSchema.parse(await request.json());const supabase=createAdminClient();const{data,error}=await supabase.from("sales_pipeline").upsert({...body,next_follow_up_on:body.next_follow_up_on||null,notes:body.notes||null,opening_order_value:body.opening_order_value===""?null:body.opening_order_value,ordered_on:body.ordered_on||null,reorder_follow_up_on:body.reorder_follow_up_on||null,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"contact_id"}).select("*").single();if(error)throw error;const{error:auditError}=await supabase.from("audit_events").insert({action:"sales_pipeline_updated",entity_type:"sales_pipeline",entity_id:data.id,actor_id:user.id,metadata:{contactId:data.contact_id,stage:data.stage,nextFollowUpOn:data.next_follow_up_on,reorderFollowUpOn:data.reorder_follow_up_on}});if(auditError)throw auditError;return NextResponse.json({pipeline:data})}catch(error){const message=error instanceof Error?error.message:"Unable to save pipeline.";return NextResponse.json({error:message==="UNAUTHORIZED"?"Sign in is required.":message==="FORBIDDEN"?"Assigned team access is required.":message},{status:message==="UNAUTHORIZED"?401:message==="FORBIDDEN"?403:400})}}
